---
version: "2.1"
services:
  chitubox-novnc:
    image: ghcr.io/maximus48p/chitubox-novnc:v0.0.1
    container_name: chitubox-novnc
    environment:
      - SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"
      #- NVIDIA_DRIVER_CAPABILITIES="all"
      #- NVIDIA_VISIBLE_DEVICES="all"
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    ports:
      - 8080:8080
    restart: unless-stopped
